# Datei: github/hello-world/.github/workflows/start.yml
name: CI
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check syntax of html files
      run: npx prettier *.html
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rsync file to our server ls home
      run: ls -la ~/
    - name: Rsync file to our server ls .ssh
      run: ls -la ~/.ssh
    - name: mkdir .ssh and install key
      shell: bash
      env:
        SSH_KEY: ${{ secrets.SshKey }}
      run: |
        if [ ! -d ~/.ssh ]; then mkdir ~/.ssh; fi
        echo $SSH_KEY > ~/.ssh/key
        chmod 600 ~/.ssh/key
        rsync -rv -i ~/.ssh/key $GITHUB_WORKSPACE/*.(html|css|js) bernd@komplett.cc:/var/www/test/

